name: build-ubuntu

env:
  BUILD_TYPE: Release

# Triggers the workflow on push or pull request events
on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        mcu: [ G431, G474 ]

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 # Fetch all history for all branches and tags
        fetch-tags: true

    - name: Install Arm GNU Toolchain (arm-none-eabi-gcc)
      uses: carlosperate/arm-none-eabi-gcc-action@v1
      with:
        release: '14.2.Rel1' # <-- The compiler release to use

    - name : Create build directory
      run: mkdir -p build-${{ matrix.mcu }}

    - name: build
      working-directory: ./build-${{ matrix.mcu }}
      run: |
        cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DTARGET_MCU=${{ matrix.mcu }} ..
        make -j4

    - name: Upload Artifacts HEX
      uses: actions/upload-artifact@v4
      with:
        name: "firmware_${{ matrix.mcu }}_HEX"
        path: ${{runner.workspace}}/OpenPixelOSD/build-${{ matrix.mcu }}/*.hex

    - name: Upload Artifacts BIN
      uses: actions/upload-artifact@v4
      with:
        name: "firmware_${{ matrix.mcu }}_BIN"
        path: ${{runner.workspace}}/OpenPixelOSD/build-${{ matrix.mcu }}/*.bin
